# Generated by Django 3.1.1 on 2020-09-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produc',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
