# Generated by Django 3.1.1 on 2020-09-15 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200915_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 15, 11, 58, 29, 54033)),
        ),
    ]
